language: python

python:
    - "3.6.3"

services:
    - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml

test:
    adapter: postgresql
    database: travis_ci_test

install:
    - pip install -r requirements.txt

script:
    - python manage.py test

env:
    - TRAVIS_SECURE_ENV_VARS = true